---

- name: fish aliases | Add aliases
  lineinfile:
    dest: "{{ fish_aliases_path }}"
    create: yes
    mode: 0644
    line: 'alias {{ item.alias }} "{{ item.command }}"'
    regexp: "^alias {{ item.alias }} "
  with_items: "{{ fish_aliases }}"
  when: fish_aliases != false
  tags: aliases

- name: fish aliases | Add extra
  lineinfile:
    dest: "{{ fish_aliases_path }}"
    create: yes
    mode: 0644
    line: "{{ item }}"
  with_items: "{{ fish_aliases_extra }}"
  when: fish_aliases_extra != false
  tags: aliases