---
- name: Setup defaults
  tags: preferences
  command:  "{{ item }}"
  with_items: 
    # Set Dock icon size and make it immutable
    - defaults write com.apple.dock tilesize -int 24
    - defaults write com.apple.dock size-immutable -bool yes


    # Set Screenshots location
    - defaults write com.apple.screencapture location '~/Library/Mobile Documents/com~apple~CloudDocs/Pictures/Screenshots'
    
    # Set Scrollbar to WhenScrolling
    - defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"
    
    # Set sidebar icon size to small
    - defaults write NSGlobalDomain "NSTableViewDefaultSizeMode" -int "1"
    - killall SystemUIServer

    # Disable Click to show Desktop
    - defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false  

    # Disable recent applications in Dock
    - defaults write com.apple.dock show-recents -bool false

    # killall Dock
    - killall Dock

- name: Setup Finder Preferences
  tags: preferences
  command: "{{ item }}"
  with_items:
    # Show Path bar in Finder 
    - defaults write com.apple.finder ShowPathbar -bool true

    # Show Status bar in Finder
    - defaults write com.apple.finder ShowStatusBar -bool true

    # Show Folders first on Desktop and Finder
    - defaults write com.apple.finder "_FXSortFoldersFirstOnDesktop" -bool "true"
    - defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

    # Set default search scope to current folder
    - defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"

    # Hide recent tags
    - defaults write com.apple.Finder ShowRecentTags -bool false

    # New Finder windows points to home
    - defaults write com.apple.finder NewWindowTarget -string "PfHm"

    # Show AirDrop in Finder Sidebar
    - defaults write com.apple.finder ShowAirDrop -bool true

    # Show Movies in Finder 
    - defaults write com.apple.finder ShowMoviesFolder -bool true

    # Show Music in Finder 
    - defaults write com.apple.finder ShowMusicFolder -bool true

    # Show Pictures in Finder
    - defaults write com.apple.finder ShowPicturesFolder -bool true

    # Show Home in Finder
    - defaults write com.apple.finder ShowHomeFolder -bool true

    # Allow text selection in Quick Look
    - defaults write com.apple.finder QLEnableTextSelection -bool true
    - killall Finder

- name: Setup Safari Preferences
  tags: preferences
  command: "{{ item }}"
  with_items:
    # Enable Safari’s debug menu 
    - defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

    # Enable the Develop menu and the Web Inspector in Safari
    - defaults write com.apple.Safari IncludeDevelopMenu -bool true

    # Enable “Do Not Track”
    - defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

    # Always Show Tab Bar
    - defaults write com.apple.Safari AlwaysShowTabBar -bool true

    # Show Favorites Bar
    - defaults write com.apple.Safari ShowFavoritesBar -bool true
    - defaults write com.apple.Safari ShowFavoritesBar-v2 -bool true

    # Show Status Bar
    - defaults write com.apple.Safari ShowStatusBar -bool true

    # Manually delete browsing history
    - defaults write com.apple.Safari HistoryAgeInDaysLimit -int 0


  
- name: Setup System Preferences
  tags: preferences
  command: "{{ item }}"
  with_items: 
    # Disable automatic capitalization as it’s annoying when typing code
    - defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

    # Disable smart dashes as they’re annoying when typing code
    - defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

    # Disable automatic period substitution as it’s annoying when typing code
    - defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

    # Disable smart quotes as they’re annoying when typing code
    - defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

    # Disable auto-correct
    - defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

- name: Setup Trackpad, Mouse and Keyboard Preferences
  tags: preferences
  command: "{{ item }}"
  with_items: 
    # Trackpad: enable tap to click for this user and for the login screen
    - defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
    - defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    - defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    
    # Disable “natural” (Lion-style) scrolling
    - defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false
    
    # Increase sound quality for Bluetooth headphones/headsets
    - defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
    
    # Enable full keyboard access for all controls
    # (e.g. enable Tab in modal dialogs)
    - defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
    
    # Set Key Repeat to Fastest
    - defaults write NSGlobalDomain KeyRepeat -int 0

